server:
  port: 8082

spring:
  application:
    name: videoservice
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/do_an?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: nghvpbm28122004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    com:
      example:
        videoservice: INFO
    org:
      springframework:
        web: INFO

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: videos

jwt:
  secret: ${JWT_SECRET_KEY:enhNPiN2TjlLKiJMcCE1UkBqVyYzZihCX21TNnQ/WVt1RTFxKUE0ZFhoN2dDekorVi1QMG9JOHdRL0x+eEcnew==}
  expiration: 3600000